# Generated by Django 5.0.1 on 2024-01-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlshortener",
            name="expiration_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
